// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeLh1Uq_nzjHZkWIIsM22htmIYle8elfg',
    appId: '1:938319153925:web:8d7ece8c765c38c97ac56c',
    messagingSenderId: '938319153925',
    projectId: 'wellby-digital',
    authDomain: 'wellby-digital.firebaseapp.com',
    storageBucket: 'wellby-digital.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfDb-SoEgJikZJ8mYPBqcEtjIbZZCxs2w',
    appId: '1:938319153925:android:adc9092ef9fb32f47ac56c',
    messagingSenderId: '938319153925',
    projectId: 'wellby-digital',
    storageBucket: 'wellby-digital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1hz7T7j-0T3yGD7F6dysjlVk1o1A_Y0g',
    appId: '1:938319153925:ios:4753e542202113197ac56c',
    messagingSenderId: '938319153925',
    projectId: 'wellby-digital',
    storageBucket: 'wellby-digital.firebasestorage.app',
    iosBundleId: 'com.example.wellby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1hz7T7j-0T3yGD7F6dysjlVk1o1A_Y0g',
    appId: '1:938319153925:ios:4753e542202113197ac56c',
    messagingSenderId: '938319153925',
    projectId: 'wellby-digital',
    storageBucket: 'wellby-digital.firebasestorage.app',
    iosBundleId: 'com.example.wellby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeLh1Uq_nzjHZkWIIsM22htmIYle8elfg',
    appId: '1:938319153925:web:6a415063b5f7a1937ac56c',
    messagingSenderId: '938319153925',
    projectId: 'wellby-digital',
    authDomain: 'wellby-digital.firebaseapp.com',
    storageBucket: 'wellby-digital.firebasestorage.app',
  );
}